version: '3'

services:
    lavalink-service:
        build: 
            context: .
            dockerfile: Dockerfile
        ports:
            - 2333
    discord-service:
        build:
            context: .
            dockerfile: local.Dockerfile
        depends_on: 
            - lavalink-service