version: '3'

services:
    bot:
      build: .
      container_name: BumblebeeBot
      depends_on:
        - audio
      restart: on-failure
  
    audio:
      container_name: BumblebeeBot-audio
      image: fredboat/lavalink:master-v3
      restart: on-failure
      volumes: 
        - ./config/application.yml:/opt/Lavalink/application.yml:ro