version: '3'

services:
    lavalink-service:
        build: 
            context: .
            dockerfile: Dockerfile
        ports:
            - 2333
        network_mode: "bridge"
    discord-service:
        build:
            context: .
            dockerfile: local.Dockerfile